// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwexzhfzqbeppuobvqnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3ZXh6aGZ6cWJlcHB1b2J2cW5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5Njg4NTgsImV4cCI6MjA3MTU0NDg1OH0.JZfzELig6U4ElDM-RGEYUOgSE-73OopnZRAwclTL2dw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});